name = "indus-foundry-ventures"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
pages_build_output_dir = ".open-next"

[vars]
# Production environment variables (DO NOT store secrets here — use `wrangler secret put`)
